# Generated by Django 4.0.3 on 2022-04-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstatus',
            name='status',
            field=models.CharField(choices=[('incoming', 'incoming'), ('past', 'past')], max_length=25),
        ),
    ]
