# Generated by Django 4.0.3 on 2022-03-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('sales_member', 'sales_member'), ('support_member', 'support_member'), ('admin', 'admin_member')], max_length=25, null=True),
        ),
    ]
