# Generated by Django 4.0.3 on 2022-04-05 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('accounts', '0002_remove_user_admin_remove_user_staff_alter_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Client',
        ),
    ]
