# Generated by Django 4.0.3 on 2022-04-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('sales_member', 'sales_member'), ('support_member', 'support_member'), ('admin', 'admin_member')], default='NONE', max_length=25, null=True),
        ),
    ]
